name: Node.js CI (Proxy)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: pnpm --filter proxy i
      - run: pnpm run build:proxy
      - run: pnpm run test:proxy
